/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mahmoud_INTERFACE1 (void);
GtkWidget* create_mahmoud_INTERFACE2 (void);
GtkWidget* create_maissa_1 (void);
GtkWidget* create_maissa_2 (void);
GtkWidget* create_maissa_3 (void);
GtkWidget* create_maissa_4 (void);
GtkWidget* create_Louay2 (void);
GtkWidget* create_Jamel1 (void);
GtkWidget* create_jamel_2 (void);
GtkWidget* create_WindowAzizUserLogin (void);
GtkWidget* create_windowAdminConnected (void);
GtkWidget* create_windowGestionnaireUtilisateurs (void);
GtkWidget* create_windowAddUsern (void);
GtkWidget* create_windowUserAddedSucc (void);
GtkWidget* create_windowAreUSure (void);
GtkWidget* create_yahAzizListeElections (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_yah_aziz_ajouter_moudifier (void);
GtkWidget* create_Louay1 (void);
GtkWidget* create_jamel3_JE (void);
GtkWidget* create_Supp_JE (void);
GtkWidget* create_dialog3 (void);
GtkWidget* create_dialog4 (void);
GtkWidget* create_stat (void);
GtkWidget* create_stat_reclamation_et_observateurs (void);
