/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *mahmoud_INTERFACE1;
  GtkWidget *mahmoud_INTERFACE2;
  GtkWidget *maissa_1;
  GtkWidget *maissa_2;
  GtkWidget *maissa_3;
  GtkWidget *maissa_4;
  GtkWidget *Louay2;
  GtkWidget *Jamel1;
  GtkWidget *jamel_2;
  GtkWidget *WindowAzizUserLogin;
  GtkWidget *windowAdminConnected;
  GtkWidget *windowGestionnaireUtilisateurs;
  GtkWidget *windowAddUsern;
  GtkWidget *windowUserAddedSucc;
  GtkWidget *windowAreUSure;
  GtkWidget *yahAzizListeElections;
  GtkWidget *dialog2;
  GtkWidget *yah_aziz_ajouter_moudifier;
  GtkWidget *Louay1;
  GtkWidget *mahmoud_interface3_MG;
  GtkWidget *jamel3_JE;
  GtkWidget *Supp_JE;
  GtkWidget *dialog3;
  GtkWidget *dialog4;
  GtkWidget *stat;
  

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*mahmoud_INTERFACE1 = create_mahmoud_INTERFACE1 ();
  gtk_widget_show (mahmoud_INTERFACE1);*/
  /*mahmoud_INTERFACE2 = create_mahmoud_INTERFACE2 ();
  gtk_widget_show (mahmoud_INTERFACE2);
  maissa_1 = create_maissa_1 ();
  gtk_widget_show (maissa_1);
  maissa_2 = create_maissa_2 ();
  gtk_widget_show (maissa_2);
  maissa_3 = create_maissa_3 ();
  gtk_widget_show (maissa_3);
  maissa_4 = create_maissa_4 ();
  gtk_widget_show (maissa_4);*/
  //Louay2 = create_Louay2 ();
 // gtk_widget_show (Louay2);
 // Jamel1 = create_Jamel1 ();
  //gtk_widget_show (Jamel1);
  //jamel_2 = create_jamel_2 ();
  //gtk_widget_show (jamel_2);
  //WindowAzizUserLogin = create_WindowAzizUserLogin ();
  //gtk_widget_show (WindowAzizUserLogin);
  /*windowAdminConnected = create_windowAdminConnected ();
  gtk_widget_show (windowAdminConnected);
  windowGestionnaireUtilisateurs = create_windowGestionnaireUtilisateurs ();
  gtk_widget_show (windowGestionnaireUtilisateurs);
  windowAddUsern = create_windowAddUsern ();
  gtk_widget_show (windowAddUsern);
  windowUserAddedSucc = create_windowUserAddedSucc ();
  gtk_widget_show (windowUserAddedSucc);
  windowAreUSure = create_windowAreUSure ();
  gtk_widget_show (windowAreUSure);
  yahAzizListeElections = create_yahAzizListeElections ();
  gtk_widget_show (yahAzizListeElections);
  dialog2 = create_dialog2 ();
  gtk_widget_show (dialog2);
  yah_aziz_ajouter_moudifier = create_yah_aziz_ajouter_moudifier ();
  gtk_widget_show (yah_aziz_ajouter_moudifier);*/
  //Louay1 = create_Louay1 ();
  //gtk_widget_show (Louay1);
  //mahmoud_interface3_MG = create_mahmoud_interface3_MG ();
  //gtk_widget_show (mahmoud_interface3_MG);*/
  //jamel3_JE = create_jamel3_JE ();
  //gtk_widget_show (jamel3_JE);
 // Supp_JE = create_Supp_JE ();
  //gtk_widget_show (Supp_JE);
  /*dialog3 = create_dialog3 ();
  gtk_widget_show (dialog3);
  dialog4 = create_dialog4 ();
  gtk_widget_show (dialog4);*/
  //stat = create_stat ();
 // gtk_widget_show (stat);
WindowAzizUserLogin = create_WindowAzizUserLogin ();
  gtk_widget_show (WindowAzizUserLogin);
 
  gtk_main ();
  return 0;
}

